### ISSUE TITLE
`bedtools_intersect`: failing unit test

### ISSUE THREAD

**Issue by rcannood** [viash-hub/biobox#135]
Hi @tgaspe !

[`bedtools_intersect`](https://github.com/viash-hub/biobox/blob/9fc07f6c05879f8efff441767ec489bb24fdce7d/src/bedtools/bedtools_intersect/config.vsh.yaml) is not passign all of it's unit tests:

    +/tmp/viash_test_bedtools_intersect_14666924159864434615/test_test/test_executable ---cpus=2 ---memory=14gb
    Notice:  Checking if Docker image is available at 'bedtools/bedtools_intersect:test'
    Warning:  Could not pull from 'bedtools/bedtools_intersect:test'. Docker image doesn't exist or is not accessible.
    Notice:  Building container 'bedtools/bedtools_intersect:test' with Dockerfile
    Creating Test Data...
    > Run bedtools_intersect on BED files with default intersect
    - test1 succeeded -
    > Run bedtools_intersect on BED files with -wa option
    - test2 succeeded -
    > Run bedtools_intersect on BED files with -wb option
    - test3 succeeded -
    > Run bedtools_intersect on BED files with -loj option
    - test4 succeeded -
    > Run bedtools_intersect on BED files with -wo option
    - test5 succeeded -
    > Run bedtools_intersect on BED files with -u option
    - test6 succeeded -
    > Run bedtools_intersect on BED files with -c option
    - test7 succeeded -
    > Run bedtools_intersect on BED files with -f 0.50 option
    - test8 succeeded -
    > Run bedtools_intersect on BED files with -f 0.30 option
    - test9 succeeded -
    > Run bedtools_intersect on BED files with -f 0.10 option
    - test10 succeeded -
    > Run bedtools_intersect on BED files with -r option
    - test11 succeeded -
    > Run bedtools_intersect on multiple BED files
    - test12 succeeded -
    > Run bedtools_intersect on GFF files
    0a1
    > ##gff-version 3
    Files are not identical!

Can you take a look?

**Comment by tgaspe** [comment]
Hi Robrecht, I figured it out the bug I will  create a new PR. 
The par_header argument is never unset in the script.sh.

**Comment by tverbeiren** [comment]
@tgaspe Can you please update me on the progress?

The bug is currently in `main` and every CI run fails on it.

**Comment by tgaspe** [comment]
Hi, Toni. 
I had addressed the bug on PR #136. (https://github.com/viash-hub/biobox/pull/136).
